### ISSUE TITLE
PNG-based PEP avatars not working on the Wasm branch

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-web#10] opened 2023-08-15 10:34 UTC
Avatar for JID: valerian@valeriansaliou.name does not show at all, where it used to work on the JS branch. Note that this only applies to PNG avatars, JPEG ones work on the Wasm branch, while PNGs do not.

**Comment by nesium** [comment] 2023-08-17 12:15
This is the avatar payload for said JID…

```xml
<message type='headline' xmlns='jabber:client' to='marc@prose.org/web' id='ttecB0ZAAFQ15ABYyngqz8LT' xml:lang='en' from='valerian@valeriansaliou.name'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
    <items node='urn:xmpp:avatar:metadata'>
      <item id='6a36724dc50dbf6b4e9776c62e37c90a47dc60a2' publisher=''>
        <metadata xmlns='urn:xmpp:avatar:metadata'>
          <info type='image/png' id='6a36724dc50dbf6b4e9776c62e37c90a47dc60a2' bytes='50584' />
        </metadata>
      </item>
    </items>
  </event>
</message>
```

The error is `JID parsing error: no domain found in this JID`.

So the problem is the empty string in `publisher` and the parsing fails on the xmpp-rs side.

**Comment by nesium** [comment] 2023-08-17 12:38
Current decision is to ignore this issue since the payload is invalid. Thus l'll close this issue.

We're still discussing this in the xmpp-rs repo: https://gitlab.com/xmpp-rs/xmpp-rs/-/issues/98

**Closed by nesium** 2023-08-17 12:38 UTC
